---
title: "ReadCensusFiles"
author: "Alan Jackson"
date: "July 8, 2018"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(ggmap)
library(rgeos)
library(sf)
library(lwgeom)
library(purrr)

options(stringsAsFactors = FALSE)

knitr::opts_chunk$set(echo = TRUE)
```

## read Community Survey gdb files

https://www2.census.gov/geo/tiger/TIGER_DP/

```{r Read ACS gdb files}

#   Read files from 2010 to 2016 (the latest)
#---------------------------------------------------------
#                         Read 2010
#---------------------------------------------------------
for (yr in seq(10,10)) {
  folder <- paste0("/home/ajackson/Dropbox/Rprojects/CensusDataframe/CensusData/20",yr,"_ACS_5YR_BG_48/")
  print(folder)
  filename <- paste0("20", yr, "_ACS_5YR_BG_48_TEXAS.gdb")
  censuslayers <- st_layers(paste0(folder, filename))
  layername <- paste0("ACS_20", yr, "_5YR_BG_48_TEXAS")
  censusdata <- st_read(paste0(folder, filename), layer = layername) %>%
    rename(COUNTYFP=COUNTYFP10, TRACTCE=TRACTCE10, BLKGRPCE=BLKGRPCE10) %>%
    filter(COUNTYFP==201) %>%
    select(TRACTCE, BLKGRPCE, B01002e1, B01002e2, B01002e3, B02001e1, B02001e2, B02001e3, B02001e4, B02001e5, B03002e12, B19013e1)

  names(censusdata) <- c("Tract", "BlkGrp", "MedAge", "MedAgeMale", "MedAgeFemale", "Pop", "White", "Black", "Amerind", "Asian", "Hispanic", "MedIncome")
  
  saveRDS(censusdata, file = paste0("~/Dropbox/Rprojects/CensusDataframe/CensusData/HarrisCounty_", yr, ".rds"))
}
#---------------------------------------------------------
#                 Read 2011
#---------------------------------------------------------
for (yr in seq(11,11)) {
  folder <- paste0("/home/ajackson/Dropbox/Rprojects/CensusDataframe/CensusData/20",yr,"_ACS_5YR_BG_48/")
  print(folder)
  filename <- paste0("20", yr, "_ACS_5YR_BG_48_TEXAS.gdb")
  censuslayers <- st_layers(paste0(folder, filename))
  layername <- paste0("ACS_20", yr, "_5YR_BG_48_TEXAS")
  censusdata <- st_read(paste0(folder, filename), layer = layername) %>%
    filter(COUNTYFP==201) %>%
    select(TRACTCE, BLKGRPCE, B01002e1, B01002e2, B01002e3, B02001e1, B02001e2, B02001e3, B02001e4, B02001e5, B03002e12, B19013e1)

  names(censusdata) <- c("Tract", "BlkGrp", "MedAge", "MedAgeMale", "MedAgeFemale", "Pop", "White", "Black", "Amerind", "Asian", "Hispanic", "MedIncome")
  
  saveRDS(censusdata, file = paste0("~/Dropbox/Rprojects/CensusDataframe/CensusData/HarrisCounty_", yr, ".rds"))
}
#---------------------------------------------------------
#                 Read 2012-2016
#---------------------------------------------------------

for (yr in seq(12,16)) {
  folder <- paste0("/home/ajackson/Dropbox/Rprojects/CensusDataframe/CensusData/20",yr,"_ACS_5YR_BG_48/")
  print(folder)
  filename <- paste0("ACS_20", yr,"_5YR_BG_48_TEXAS.gdb") 
  layername <- paste0("ACS_20", yr, "_5YR_BG_48_TEXAS")

censusdata <- c(layername, "X01_AGE_AND_SEX", "X02_RACE", "X03_HISPANIC_OR_LATINO_ORIGIN", "X19_INCOME") %>%
  map_dfc(~st_read(paste0(folder, filename), layer = .)) %>%
  filter(COUNTYFP==201) %>% 
  select(TRACTCE, BLKGRPCE, B01002e1, B01002e2, B01002e3, B02001e1, B02001e2, B02001e3, B02001e4, B02001e5, B03002e12, B19013e1)
    
  names(censusdata) <- c("Tract", "BlkGrp", "MedAge", "MedAgeMale", "MedAgeFemale", "Pop", "White", "Black", "Amerind", "Asian", "Hispanic", "MedIncome")
  
  saveRDS(censusdata, file = paste0("~/Dropbox/Rprojects/CensusDataframe/CensusData/HarrisCounty_", yr, ".rds"))
}


```


##     Read in zip code files - really ZCTA files

Get polygons for ZCTA areas from https://www2.census.gov/geo/tiger/TIGER_DP/

Get the data from ACS_??_5YR_DP05_with_ann.csv files where ?? = year from 2011-2016

```{r read zipcode files}
#---------------------------------------------------------
#                 Read 2011-2012
#---------------------------------------------------------

folder <- paste0("/home/ajackson/Dropbox/Rprojects/CensusDataframe/CensusData/zipcodefiles/")

for (yr in seq(11,12)) {
  filename <- paste0(folder,"ACS_", yr,"_5YR_DP05_with_ann.csv") 

  censusdf <- read.csv(filename) %>%
    select(GEO.id2, HC01_VC03, HC01_VC04, HC01_VC07, HC01_VC08, HC01_VC09, HC01_VC10, HC01_VC11, HC01_VC12, HC01_VC13, HC01_VC14, HC01_VC15, HC01_VC16, HC01_VC17, HC01_VC18, HC01_VC19, HC01_VC21, HC01_VC43, HC01_VC44, HC01_VC82 ) %>%
    filter(GEO.id2 != "Id2") %>%
    type_convert()
  
    names(censusdf) <- c("ZCTA", "Pop", "MalePop", "Age0to4", "Age5to9", "Age10to14", "Age15to19", "Age20to24", "Age25to34", "Age35to44", "Age45to54", "Age55to59", "Age60to64", "Age65to74", "Age75to84", "Age85andup", "MedianAge", "White", "Black", "Hispanic") 
    
    saveRDS(censusdf, file = paste0("~/Dropbox/Rprojects/CensusDataframe/CensusData/TexasZipcode_", yr, ".rds"))
} # end yr 11, 12

#---------------------------------------------------------
#                 Read 2013 - 2016
#---------------------------------------------------------

for (yr in seq(13,16))  {
  print(paste0("---",yr,"---"))
  filename <- paste0(folder,"ACS_", yr,"_5YR_DP05_with_ann.csv") 
  censusdf <- read.csv(filename) %>%
    select(GEO.id2, HC01_VC03, HC01_VC04, HC01_VC08, HC01_VC09, HC01_VC10, HC01_VC11, HC01_VC12, HC01_VC13, HC01_VC14, HC01_VC15, HC01_VC16, HC01_VC17, HC01_VC18, HC01_VC19, HC01_VC20, HC01_VC23, HC01_VC49, HC01_VC50, HC01_VC88 ) %>%
    filter(GEO.id2 != "Id2") %>%
    type_convert()
  
    names(censusdf) <- c("ZCTA", "Pop", "MalePop", "Age0to4", "Age5to9", "Age10to14", "Age15to19", "Age20to24", "Age25to34", "Age35to44", "Age45to54", "Age55to59", "Age60to64", "Age65to74", "Age75to84", "Age85andup", "MedianAge", "White", "Black", "Hispanic") 
    
    saveRDS(censusdf, file = paste0("~/Dropbox/Rprojects/CensusDataframe/CensusData/TexasZipcode_", yr, ".rds"))
} # end yr 13:16
    
#---------------------------------------------------------
#                 Read 2010
#---------------------------------------------------------

folder <- paste0("/home/ajackson/Dropbox/Rprojects/CensusDataframe/CensusData/zipcodefiles/")

yr <- "10"

filename <- paste0(folder,"DEC_", yr,"_SF1_SF1DP1_with_ann.csv") 

censusdf <- read.csv(filename) %>%
    select(GEO.id2, HD01_S001, HD01_S026, HD01_S002, HD01_S003, HD01_S004, HD01_S005, HD01_S006, HD01_S007, HD01_S008, HD01_S009, HD01_S010, HD01_S011, HD01_S012, HD01_S013, HD01_S014, HD01_S015, HD01_S016, HD01_S017, HD01_S018, HD01_S019, HD01_S020, HD01_S078, HD01_S079, HD01_S107) %>%
    filter(GEO.id2 != "Id2") %>%
  type_convert()
    
names(censusdf) <- c("ZCTA", "Pop", "MalePop", "Age0to4", "Age5to9", "Age10to14", "Age15to19", "Age20to24", "Age25to29", "Age30to34", "Age35to39", "Age40to44", "Age45to49", "Age50to54", "Age55to59", "Age60to64", "Age65to69", "Age70to74", "Age75to79", "Age80to84", "Age85andup", "MedianAge", "White", "Black", "Hispanic") 
  
censusdf <- censusdf %>%
  mutate(Age25to34=Age25to29+Age30to34) %>% 
  mutate(Age35to44=Age35to39+Age40to44) %>% 
  mutate(Age45to54=Age45to49+Age50to54) %>%
  select(-c(Age25to29, Age30to34, Age35to39, Age40to44, Age45to49, Age50to54)) %>%
    type_convert()

saveRDS(censusdf, file = paste0("~/Dropbox/Rprojects/CensusDataframe/CensusData/TexasZipcode_", yr, ".rds"))


```

##     Read in zip code polygon files - really ZCTA files

Get polygons for ZCTA areas from https://www2.census.gov/geo/tiger/TIGER_DP/

```{r zipcode polygons}

folder <- paste0("/home/ajackson/Dropbox/Rprojects/CensusDataframe/CensusData/zipcodefiles/")
filename <- "ACS_2016_5YR_ZCTA.gdb"

censuslayers <- st_layers(paste0(folder, filename))

layername <- "ACS_2016_5YR_ZCTA"

ZCTApolys <- st_read(paste0(folder, filename), layer = layername) %>%
  select(-c(GEOID10, CLASSFP10, MTFCC10, FUNCSTAT10))

ZCTApolys <- st_transform(ZCTApolys, 4326) # reproject to Google epsg code


  saveRDS(ZCTApolys, file = "~/Dropbox/Rprojects/CensusDataframe/ZCTA_polygons_2016.rds")


```

